### ISSUE TITLE
Possible bug in caching

### ISSUE THREAD

**Issue by jackkoenig** [sifive/wake#18] opened 2019-01-09 21:04 UTC
This is using wake v0.5

Given the following directory structure:
```
$ tree
.
├── build.wake
├── foo
│   ├── bar
│   │   └── file2
│   └── file1
$ cat build.wake
global def peek _ =
  def dir = simplify "{here}/foo"
  def all = files dir '.*'
  def top = dir, Nil
  def cmd = which "ls", "-R", dir, Nil
  (job cmd all).stdout
```
Notably, see `all` and `top` as alternative arguments to `job`.
If we keep it as above and run wake we get the following:
```
koenig@gamma04:/scratch/koenig/wake-experiment$ wake -dv peek 0
Running 32 jobs at a time.
<hash> foo/bar/file2 
<hash> foo/file1 
23851bfa7da72af0b9cb11da106601d1
23851bfa7da72af0b9cb11da106601d1
OK: .build/23905/bin/ls -R foo 
foo:
bar
file1

foo/bar:
file2
peek 0: String = "foo:\nbar\nfile1\n\nfoo/bar:\nfile2\n"
```
As expected, it can see all of the files under `foo`, but if I modify `build.wake` to use `top` instead of `all`:
```
koenig@gamma04:/scratch/koenig/wake-experiment$ wake -dv peek 0
Running 32 jobs at a time.
<hash> foo 
00000000000000000000000000000000
peek 0: String = "foo:\nbar\nfile1\n\nfoo/bar:\nfile2\n"
```
It does not rerun the job, and returns a cached result.
But if I delete the wake.db and run again, it gets a different result:
```
$ rm -rf wake.db
$ wake --init .
$ wake -dv peek 0
Running 32 jobs at a time.
<hash> foo 
00000000000000000000000000000000
OK: .build/24775/bin/ls -R foo 
foo:
peek 0: String = "foo:\n"
```

**Comment by terpstra** [comment] 2020-12-17 22:56
Duplicate of #427

**Comment by V-FEXrt** [comment] 2023-02-24 00:18
Closing this since it is duped to #427

**Closed by V-FEXrt** 2023-02-24 00:18 UTC
Labels: bug, enhancement, 1.0
