### ISSUE TITLE
Invalidate jobs in the database

### ISSUE THREAD

**Issue by albertchen-sifive** [sifive/wake#423] opened 2020-04-17 16:44 UTC
When I'm writing wake rules, a lot of times I'll mess up an `OutputFn` or a `Runner` and my job will run incorrectly and I won't be able to rerun in because it was stored in the database incorrectly. For example, my output filter function might have incorrectly filtered all the files and now the the job is recorded in the database with no outputs. When it is in this state I need to use `setPlanPersistence ReRun` or delete the database.

It would be helpful if there was an easy way to lookup and delete jobs from the database. or maybe something like a `wake --prune target` that would delete all jobs from the database that were not required to run the target. For example `wake --prune -x compileScalaModule rocketChipScalaModule` would be very useful because scala compile usually takes the longest and so many jobs depend on scala compilation.

**Comment by richardxia** [comment] 2020-04-17 18:55
Could I also request that we have an option to specify a job to invalidate based on its Job ID? There's usually a straightforward way to find the ID of a Job you're interested in, such as running `wake -o` on a file you know it produced or by just running `wake --last` or `wake --failed`.

**Comment by terpstra** [comment] 2020-04-17 19:13
This has already been fixed in 0.18.0. See the ChangeLog entry:
```
Changing a Plan's Fn{Inputs,Outputs,Resources} now triggers a rebuild
```

The related PR was: https://github.com/sifive/wake/pull/315

**Comment by terpstra** [comment] 2020-04-17 19:16
This does not help with Runners, but my hope for 0.19 is that Runners become a thing of the past and wake will catch changes to their replacement and trigger a rebuild, like how FnOutputs works now.

**Comment by terpstra** [comment] 2020-04-17 19:16
@richardxia If you want to rerun a job, and you know one of its outputs... Just delete that output.

**Comment by erikdanie** [comment] 2020-04-28 21:00
I often have cases where a long job (fpga build) fails, but if I want to rerun with the -d flag. Maybe it fails to produce outputs, or I don't want to have it run all its `Job`s again because they take forever, so I need to change the actual source code slightly (usually I just add print statements) in order to invalidate the build enough to cause it to rerun with -d. It would be nice to have a cleaner interface for this

**Comment by terpstra** [comment] 2020-04-28 21:07
Adding '-d' to the command-line also counts as a change. How do you get it to not rerun the dependents??

**Comment by terpstra** [comment] 2020-04-28 21:08
Also, if it didn't produce outputs, presumably it should run again anyway. I suspect there is something wrong with the build rules if this is necessary.

**Comment by erikdanie** [comment] 2020-04-28 21:21
I admittedly have never tried just -d, assuming that it would need something to change from other experiences haha.

This particular thing doesn't cause a non-zero exit status, but it causes a Job to have no outputs (i.e. try compiling this software test, but expect some of them to fail, so just take the good ones)

**Comment by terpstra** [comment] 2020-12-17 22:32
Not a bug

**Closed by terpstra** 2020-12-17 22:32 UTC
