### ISSUE TITLE
Dry run mode

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#179] opened 2019-06-08 23:01 UTC
It would be useful to have a dry-run mode that lets me know what would be run without actually running it. It’s fine if it doesn’t produce the full dependency graph because of data dependencies between commands, but it’d be nice to have a simple way of seeing what commands would get run without having it actually run them.

**Comment by terpstra** [comment] 2019-06-09 00:44
I'm pretty sure this is impossible. Make can do this because the DAG is known up front. Wake explicitly made the decision to not have a static DAG. As a result, I don't think we can implement a useful form of this make feature. The best we could do is print all the jobs that it would run first, without seeing what comes next.

As an alternative, I could use the database to print out what it did last time... but I guess this is not what you want.

**Comment by terpstra** [comment] 2019-06-09 00:47
Part of the problem is we don't even know how many or the names of, the outputs of unexecuted Jobs.

**Comment by richardxia** [comment] 2019-06-09 04:25
In retrospect, I might just want the database. Part of my motivation for creating this issue was for solving the issue with not being able to ask wake to print out the type signature of a function when another wake process is running, and I thought a dry run mode could be helpful for that.

**Comment by terpstra** [comment] 2019-06-09 05:23
I definitely intend to make it possible to type-check things while a build is running. So if that's what you were looking for, it will be added at some point.

**Comment by terpstra** [comment] 2019-06-09 05:24
`wake --no-workspace` can at least give you types for the basis library without a lock. I know that's probably not what you want, but it's what we have right now.

**Comment by terpstra** [comment] 2019-09-30 18:53
Closing this in favour of #296.

**Closed by terpstra** 2019-09-30 18:53 UTC
